# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='futsal_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.FutsalTeam'),
        ),
    ]
