# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160331_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporthall',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.SportHallAddress'),
        ),
        migrations.AlterField(
            model_name='sporthalladdress',
            name='sport_hall',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.SportHall'),
        ),
    ]
