# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160331_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporthalladdress',
            name='sport_hall',
        ),
    ]
