# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_match_futsal_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedMatchs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('futsal_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.FutsalTeam')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Match')),
            ],
        ),
    ]
