# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_predictedmatchs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictedMatchs',
            new_name='PredictedMatch',
        ),
    ]
